### ISSUE TITLE
Feature wish

### ISSUE THREAD

**Issue by manfredlotz** [LuloDev/logseq-book-fetch#1]
It would be nice if block properties could be used for a book (chosen by settings)

```
  - Title:: some book title
     ISBN:: 98383838-1
     Authors:: John Doe
     Published Art:: ...
     ...
     Description:: what a wonderful book
```

What do you think?

**Comment by LuloDev** [comment]
Hi! Thanks for your suggestion. The current version allows users to choose which book attributes to insert in the Extension options.

![image](https://github.com/LuloDev/logseq-book-fetch/assets/134250506/f6e83181-43cd-42a9-98ad-11178eb02593)

Also, I'm thinking about adding in the next version the use of a template to customize the properties insertion. 

```
Title: {{title}} by {{authors}}
Description: {{description}}
Published At: {{publishedAt}}
```

What do you think? Does the current configuration work for you or do you think the template is better?

**Comment by manfredlotz** [comment]
If I understand correctly then the current configuration work allows to choose what I like to get. This is very good.

But it doesn't allow to choose that I like to have `::` to get block properties. So there should be either an additional option for this or perhaps the idea of a  template might give the user the best flexibility.

**Comment by LuloDev** [comment]
You can use this setting in the template option

```
- Title: {{title}}\n- Authors:: {{authors}}\n- ISBN:: {{isbn}}
```
Result:

![image](https://github.com/LuloDev/logseq-book-fetch/assets/134250506/b2718ffe-f17e-4284-ac13-1c483cfd1bbc)

Is available in the new version!!

**Comment by manfredlotz** [comment]
Doesn't work for me. On my system (Linux) I had to change all occurences of `\n` to `\\n`. Then it was working ok.
